### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by misolee** [misolee/Misora#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by misolee** [comment]
Hi Cynthia
I'm done with user Auth and I pushed it upto heroku.
Thanks!

**Comment by xnanodax** [comment]
Awesome Auth!! I unchecked the only box you need left :) (Going to a random route /#/oweiniouewbrviuwebv should redirect to either /, /login, or /signup)

**Comment by misolee** [comment]
Hi Cynthia I fixed the redirect problem! it's up on Heroku :D thank you!

**Comment by xnanodax** [comment]
Done! Great work!
