### ISSUE TITLE
products MVP

### ISSUE THREAD

**Issue by misolee** [misolee/Misora#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by xnanodax** [comment]
Let's add some more seeds so that every product has a `How to Use` and `Ingredients` page!

**Comment by xnanodax** [comment]
Looks good! Great job :)
